# -*- coding: utf-8 -*-
"""bitirme projesi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/142FNBedoHZo2vI9cLerQpuiJnfDVClqJ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import re
from datetime import datetime, timedelta
from scipy import stats
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

"""#IMPORT DATA"""

df= pd.read_csv('/content/Finance_Ecommerce_Dirty_Dataset_csv.csv')

data=df.copy()

"""#EDA

"""

pd.set_option('display.max_columns',None)
df.head()

df.tail()

df.shape

df.info()

df.columns

df.index

df.describe()

df.isnull().sum()

"""Datadakı boşlukları kaldırmak için"""

for col in df.select_dtypes(include="object").columns:
    df[col] = (
        df[col]
        .astype(str)
        .str.replace("\xa0", "", regex=False)  # gizli boşluq
        .str.strip()
        .str.replace(r"\s+", " ", regex=True)
    )

df.head()
df.select_dtypes("object").apply(lambda x: x.unique()[:5])

pd.set_option('display.max_columns',None)
df.head()

"""Date düzenliyoruz"""

df["Date"] = pd.to_datetime(df["Date"], errors="coerce", dayfirst=False)

df["CustomerSince"] = pd.to_datetime(df["CustomerSince"], errors="coerce", dayfirst=True)

"""Transaction ıd de yanlışları düzeltme"""

df["TransactionID"] = df["TransactionID"].apply(
    lambda x: "TX" + x if x.isdigit() else x
)

df["TransactionID"] = df["TransactionID"].replace("NAN", pd.NA)

missing_mask = df["TransactionID"].isna()
df.loc[missing_mask, "TransactionID"] = [
    f"TX{100000+i}" for i in range(missing_mask.sum())
]

invalid_ids = df[~df["TransactionID"].str.match(r"^TX\d+$", na=False)]

df = df.drop_duplicates(subset="TransactionID")

print("Boş ID sayı:", df["TransactionID"].isna().sum())
print("Dublikat ID sayı:", df["TransactionID"].duplicated().sum())
print("Format düzgünmü:", df["TransactionID"].str.match(r"^TX\d+$").all())
print("Format səhv ID-lər:\n", invalid_ids["TransactionID"])

"""Transaction type düzenleme"""

df["TransactionType"] = (
    df["TransactionType"]
    .astype(str)
    .str.strip()
    .str.lower()
)

mapping = {
    "debit": "Debit",
    "credit": "Credit",
    "refund": "Refund",
    "cr": "Credit",
    "dr": "Debit"
}

df["TransactionType"] = df["TransactionType"].replace(mapping)

df = df[df["TransactionType"].str.upper() != "NAN"]

print(df["TransactionType"].value_counts())

"""Currency düzenleme"""

print(df["Currency"].value_counts())

df["Currency"] = (
    df["Currency"]
    .astype(str)
    .str.strip()
    .str.upper()
)

df = df[~df["Currency"].isin(["NAN"])]  # "NaN" yazısını sil
df["Currency"] = df["Currency"].replace({
    "INRR": "INR"
})

"""Merchant ve subchategory düzenleme"""

print(df["Merchant"].value_counts())

df = df[df["Merchant"].str.upper() != "NAN"]

print(df["Subcategory"].value_counts())

df = df[df["Subcategory"].str.upper() != "NAN"]

"""Mailleri düzenleme - mailler belirli sayda olduğu üçün
mağazaya uyğunlaşdırıb sehvleri düzeldirik
"""

# Mətnləri təmizlə (strip, title case)
df["Merchant"] = df["Merchant"].astype(str).str.strip().str.title()
df["MerchantEmail"] = df["MerchantEmail"].astype(str).str.strip().str.lower()

# Mapping dictionary
merchant_email_map = df[df["MerchantEmail"].str.upper() != "NAN"]\
    .drop_duplicates(subset="Merchant")\
    .set_index("Merchant")["MerchantEmail"].to_dict()

merchant_email_map = {
    "Paytm Mall": "paytmmall@biz.com",
    "Flipkart": "flipkart@biz.com",
    "Bigbasket": "bigbasket@biz.com",
    "Amazon": "amazon@biz.com",
    "Starbucks": "starbucks@biz.com",
    "Zomato": "zomato@biz.com",
    "Localmart": "localmart@biz.com",
    "Swiggy": "swiggy@biz.com",
    "Myntra": "myntra@biz.com",
    "ShopEasy": "shopeasy@biz.com",
    "AutoZone": "autozone@biz.com",
    "Walmart": "walmart@biz.com",
    "Reliance": "reliance@biz.com",
    "Electroworld": "electroworld@biz.com"
}

mask = df["MerchantEmail"].str.upper() == "NAN"
df.loc[mask, "MerchantEmail"] = df.loc[mask, "Merchant"].map(merchant_email_map)

print(df["MerchantEmail"].value_counts())

"""IsFraud düzenle - böyük kiçik ferqleri var yanlışları düzenleyirik"""

mapping = {
    "no": "No",
    "yes": "Yes",
    "yess": "Yes",
    "Yess": "Yes",
    "nan": "No"
}

df["IsFraud"] = df["IsFraud"].replace(mapping)

print(df["IsFraud"].value_counts())

"""Postal code düzenlemek şehirlere uygun- datada şeherler uyğun postal codlar verildiyi üçün uyğunluğu tapıb düzenleyirik"""

# NaN qalmış hissələr float, digərini int
df["PostalCode"] = df["PostalCode"].apply(lambda x: int(x) if pd.notna(x) else x)

df["PostalCode"] = df["PostalCode"].apply(lambda x: str(int(x)) if pd.notna(x) else x)

postal_map = df.dropna(subset=["PostalCode"]).drop_duplicates("City").set_index("City")["PostalCode"].to_dict()

mask = df["PostalCode"].isna()
df.loc[mask, "PostalCode"] = df.loc[mask, "City"].map(postal_map)

df["PostalCode"].isna().sum()  # hələ boş varsa göstərir
df["PostalCode"].head()

"""amount ve balanceni düzenleyelim"""

for col in ["Amount", "Balance"]:
    df[col] = (
        df[col]
        .astype(str)
        .str.replace(r"[^\d.-]", "", regex=True) )
    df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0)
    df[col] = df[col].abs()

print(df[["Amount", "Balance"]].head())
print(df.dtypes[["Amount", "Balance"]])

numeric_cols = ["Amount", "Balance", "ExchangeRate"]
df[numeric_cols].head()

median_amount = df["Amount"].median()
median_balance = df["Balance"].median()
print("Amount median:", median_amount)
print("Balance median:", median_balance)

for col in numeric_cols:
    median_value = df[col].median()     # median hesabla
    df[col] = df[col].fillna(median_value)  # NaN-ları median ilə doldur

df[numeric_cols].isna().sum()  # 0 çıxmalıdır

df.shape

# NaN olmayan MerchantPhone-ları götür və hər Merchant üçün bir nümunə seç
phone_map = (
    df.dropna(subset=["MerchantEmail"])
      .drop_duplicates("Merchant")
      .set_index("Merchant")["MerchantEmail"]
      .to_dict()
)

print(phone_map)

# Merchant → Email mapping
email_map = {
    'Shopeasy': 'shopeasy@biz.com',
    'Autozone': 'autozone@biz.com',
    'Bigbasket': 'bigbasket@biz.com',
    'Localmart': 'localmart@biz.com',
    'Amazon': 'amazon@biz.com',
    'Starbucks': 'starbucks@biz.com',
    'Myntra': 'myntra@biz.com',
    'Reliance': 'reliance@biz.com',
    'Zomato': 'zomato@biz.com',
    'Flipkart': 'flipkart@biz.com',
    'Paytm Mall': 'paytmmall@biz.com',
    'Walmart': 'walmart@biz.com',
    'Electroworld': 'electroworld@biz.com',
    'Swiggy': 'swiggy@biz.com'
}

# NaN-ları doldurmaq
mask = df["MerchantEmail"].isna()
df.loc[mask, "MerchantEmail"] = df.loc[mask, "Merchant"].map(email_map)

# Yoxlama
print(df["MerchantEmail"].isna().sum())  # 0 çıxmalıdır

"""Market nömrelerinde olan sehvleri dataya uyğunlaşdırıb doldururuq

"""

# NaN olmayan MerchantPhone-ları götür və hər Merchant üçün bir nümunə seç
phone_map = (
    df.dropna(subset=["MerchantPhone"])
      .drop_duplicates("Merchant")
      .set_index("Merchant")["MerchantPhone"]
      .to_dict()
)

print(phone_map)

phone_map = {
    'Autozone': 1856170186,
    'Bigbasket': 323250652,
    'Localmart': 676286112,
    'Starbucks': 3913113314,
    'Reliance': 6381948606,
    'Shopeasy': 9150633421,
    'Zomato': 9808807153,
    'Paytm Mall': 7725198158,   # mənfi işarə götürüldü
    'Electroworld': 6028962435,
    'Myntra': 4807851195,
    'Swiggy': 7525993573,
    'Walmart': 9515266074,
    'Amazon': 9266232769,
    'Flipkart': 6699009169      # mənfi işarə götürüldü
}

mask = df["MerchantPhone"].isna()  # boş sətirlər
df.loc[mask, "MerchantPhone"] = df.loc[mask, "Merchant"].map(phone_map)

df["Amount"] = pd.to_numeric(df["Amount"], errors="coerce")
df["Amount_Base"] = df["Amount"] * df["ExchangeRate"]

"""NA-ları silirik"""

df=df.dropna(subset='Phone')

df= df.drop('CustomerSince', axis=1)

pd.set_option('display.max_columns',None)
df.head()

df["Amount_Base"] = df["Amount_Base"].round(2)

df.shape

df.isna().sum()

df.columns

df.info()

for col in df.select_dtypes(include=['object']).columns[:10]:
    print(f"{col}: {df[col].nunique():,} unikal dəyər")

"""Outlier Analizi"""

numeric_cols = df.select_dtypes(include=[np.number]).columns

for col in numeric_cols:
    if df[col].notna().sum() > 0:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR

        outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)][col].count()
        outlier_pct = outliers / len(df) * 100

        if outlier_pct > 0:
            print(f"{col}: {outliers:,} Outlier dəyər ({outlier_pct:.2f}%)")

"""#Qısa Analiz"""

desc_stats = df[['Amount_Base']].describe()
print(desc_stats)

"""Amount base yayılmasına baxırıq"""

#daha düzgün netice almaq üçün amounbasde olan aykırı deyerleri düzenlemeliyik
# Amount_Base müsbət dəyərlərə malikdirsə (0-dan böyük)
df['Amount_Base_log'] = np.log1p(df['Amount_Base'])  # log(1 + x) – 0 dəyərlər üçün təhlükəsiz
# və ya
df['Amount_Base_log'] = np.log(df['Amount_Base'])

# Orijinal və log-transformasiya olunmuş dəyərlər
original = df['Amount_Base']
log_transformed = np.log1p(df['Amount_Base'])  # log(1+x)

# Yan-yana histogram
fig, axes = plt.subplots(1, 2, figsize=(12, 4))

sns.histplot(original, bins=50, kde=True, ax=axes[0])
axes[0].set_title('Orijinal Amount_Base (Sağa çarpıq)')
axes[0].set_xlabel('Məbləğ')

sns.histplot(log_transformed, bins=50, kde=True, ax=axes[1])
axes[1].set_title('Log-transformasiya olunmuş Amount_Base (Normal yaxın)')
axes[1].set_xlabel('log(1 + Məbləğ)')

plt.tight_layout()
plt.show()

"""Bizim esas numeric columumuz Amount base olduğu üçün onda olan aykırı deyerleri düzenleyirik. Birinci qrafikdə məlumatların çoxu sıfıra yaxın olduğu üçün qutu görmürsünüz, ancaq bir neçə çox böyük aykırı dəyər var. Bu, statistik testlər üçün problemdir. İkinci qrafikdə loqarifmik transformasiya tətbiq etdik. Böyük dəyərlər kiçildi, kiçik dəyərlər bir az böyüdü. İndi bütün məlumatlar təxminən eyni miqyasda oldu, qutu görünür və paylanma normala yaxınlaşdı."""

#Ödeniş növüne göre statistik deyerleri yoxlayırıq
print("\nTRANSAKSİYA TİPİ ÜZRƏ STATİSTİKA")
tx_type_stats = df.groupby('TransactionType')['Amount_Base'].agg(['count', 'mean', 'median', 'std', 'sum'])
print(tx_type_stats)

"""Üç ödəniş növünü müqayisə etdik: Credit, Debit, Refund.
Ən çox istifadə olunan Debit kartdır (2905 əməliyyat).
Median məbləğlər üç növdə də 830–930 arasındadır – yəni tipik bir əməliyyatda müştərilər təxminən eyni pul ödəyir.
Lakin ortalama məbləğlər çox yüksəkdir (Credit-də 78 min, Debit-də 37 min). Bu fərq, hər ödəniş növü daxilində bir neçə çox böyük məbləğli əməliyyatın olması ilə izah olunur. Xüsusilə Credit-də bu böyük məbləğlər ümumi dövriyyəni (145 milyon) artırır.
Yekun: Normal istifadədə ödəniş növü məbləğə təsir etmir. Ancaq bəzi nadir böyük əməliyyatlar – xüsusilə Credit-də – ümumi statistikaları təhrif edir
"""

#Kategoriyalara göre hipotez testi
# Kateqoriya qruplarını log‑məbləğlərə görə yığın
groups = [df[df['Category'] == cat]['Amount_Base_log'].dropna() for cat in df['Category'].unique()]
f_stat, p_cat = f_oneway(*groups)
print(f"Kateqoriya ANOVA p-value: {p_cat}")

# Əvvəlcə həftə sonu sütunu yaradın
df['IsWeekend'] = df['Date'].dt.dayofweek >= 5  # 5 = Cümə, 6 = Şənbə
# Sonra iki qrupu müqayisə edin (t-test)
from scipy.stats import ttest_ind
weekend = df[df['IsWeekend'] == True]['Amount_Base_log'].dropna()
weekday = df[df['IsWeekend'] == False]['Amount_Base_log'].dropna()
t_stat, p_weekend = ttest_ind(weekend, weekday, equal_var=False)
print(f"Həftə sonu vs içi p-value: {p_weekend}")

#testin doğruluğunu yoxlamaq üçün Mann testinden isitfade edirik.
from scipy.stats import mannwhitneyu
u_stat, p_mw = mannwhitneyu(weekend, weekday, alternative='two-sided')
print(f"Mann-Whitney U p-value: {p_mw}")

# Həftə sonu və içi üçün neçə əməliyyat olduğunu göstər
print("Həftə sonu əməliyyat sayı:", len(weekend))
print("Həftə içi əməliyyat sayı:", len(weekday))

# Kateqoriyaların hər birində neçə əməliyyat var?
print(df['Category'].value_counts())

"""Hər bir kateqoriyada 500-dən çox, həftə sonu və içi qruplarında isə minlərlə əməliyyat var. Bu böyük məlumat həcmi test nəticələrinin etibarlılığını təmin edir. Həm ANOVA, həm də Mann-Whitney U testləri göstərdi ki, nə kateqoriya, nə də həftə sonu/içi fərqi əməliyyat məbləğinə təsir etmir. Yəni müştərilər bütün şəraitlərdə eyni orta məbləğdə xərcləyir."""

#Ölkeler arasında hipotez testi
top_countries = df['Country'].value_counts().head(10).index
groups_country = [df[df['Country'] == c]['Amount_Base_log'].dropna() for c in top_countries]
f_stat_c, p_country = f_oneway(*groups_country)
print(f"Ölkə ANOVA p-value: {p_country}")

"""p = 0.691 > 0.05 → H₀ rədd edilmir.

Nəticə: Fərqli ölkələrdə edilən əməliyyatların orta məbləği arasında statistik cəhətdən anlamlı fərq yoxdur. Yəni hansı ölkədə olmasından asılı olmayaraq, müştərilər təxminən eyni orta məbləği ödəyir.
"""

# Commented out IPython magic to ensure Python compatibility.
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")
# %matplotlib inline

df['Date'] = pd.to_datetime(df['Date'])
df_time = df.set_index('Date')

#en çox pul xerclenen cadegoriayalar
df.groupby("Category")["Amount_Base"].sum().sort_values(ascending=False)


#Burada gördüyümüz kimi en çox pul xerclenen kategoriya Elektronikadır.

#en çox istifade olunan Marketler
df["Merchant"].value_counts().head(10)

#Aralarında cüzi ferq olsada en çox istifade edilen market Paytm mall-dur.

#ölkeler üzre xercler
df.groupby("Country")["Amount_Base"].sum().sort_values(ascending=False)

#Ölkeler arasında en yüksek Amerikadır.

#fraud analizi (dolandırıcılıq)
df["IsFraud"].value_counts()

tx_counts = df['TransactionType'].value_counts()
fig = go.Figure(data=[go.Pie(labels=tx_counts.index, values=tx_counts.values)])
fig.update_layout(title_text='Əməliyyat Növü Paylanması')
fig.show()

#en çox ödeniş növünün Debet olduğunu görürük.

top_categories = df['Category'].value_counts().head(10)
fig_bar_chart = go.Figure(data=[go.Bar(
    x=top_categories.values[::-1],
    y=top_categories.index[::-1],
    orientation='h',
    marker_color=px.colors.qualitative.Plotly[1]
)])
fig_bar_chart.update_layout(title_text='Sayına görə Ən Yüksək Kateqoriyalar')
fig_bar_chart.show()

#en çox istifade edilen kategoriya ise yemek ve baqqal ardınca ise tehsil kategoriyasıdır

fraud_by_cat = df[df['IsFraud']=='Yes']['Category'].value_counts().head(8)[::-1]
fig_fraud_by_cat_chart = go.Figure(data=[go.Bar(x=fraud_by_cat.values, y=fraud_by_cat.index, orientation='h',
                     marker_color=colors[5])])
fig_fraud_by_cat_chart.update_layout(title_text='Fırıldaqçılıq Hallarının Kateqoriyalar Üzrə Paylanması')
fig_fraud_by_cat_chart.show()

#en çox fırıldaqçılıq geyim kategoriyasıda olduğunu göre

"""#Müşteri analizi"""

top_customers = df['AccountName'].value_counts().head(20)[::-1]

fig, ax = plt.subplots(figsize=(10,8))
ax.barh(top_customers.index, top_customers.values, color='mediumseagreen')
ax.set_title('En Aktif Müşteriler (Top 20)', fontsize=12, fontweight='bold')
ax.set_xlabel('Emelyat Sayı')
plt.tight_layout()
plt.show()
#en aktif müşterileri tapmaq üçün istifade ederik bu şekilde ona özel endirimler ve kampanyalarıda onlara suna bilerik

df.to_csv("clean_data.csv", index=False)

"""Biznes dilinde yorumlamaq:

İlk önce temizleme işlemlerini gördük.
temizlenmiş data : 5.671
düzenlenmiş esas data : Amount_base (sebebi valyunta ferqleri var idi)
Meqsed: Mebleğe tesir eden amilleri müyyen edib düzgün biznes qerarları vermek.

------------------------

Amount Base de sağa çarpıqlıq var idi yeni bezi müşterilerin yüksek ödenişleri statistik neticeye tesir edirdi. Müşterilerin 75% aşağı ödenişler edir. buna göre biz hesablama aparanda esas olaraq ortalamaya deyilde mediana baxmalıyıq.

------------------------------
Ödeniş növü
ödeniş növlerinde median mebleğler demek ölar bir birine yaxındır.
Credit- 850, Debit - 826, Refund - 931

ödeniş növüne göre xüsusi monitorinqe ehtiyac yoxdur. Ancaq Geri qaytarmaları azaltmaq üçün müeyyen şirket daxili düzenlemeler ve yoxlanışlar aparılmalıdır.

-----------------------------------
Kategoriyalara göre
her kategoriyada 521-600 arası emelyat aparılmışdır buda balanslı paylanmanı gösterir.
Ferqlenmesini ve satışın artmasını istediyimiz kategoriyada müyyen kampanyalar veya resuslar xercleye bilerik.

------------------------
Hefte sonu ve Hefte içiHefte içi - 4091 hefte sonu 1580 emelyat olmuşdur.
insanlar hefte çi daha çox ödeniş edir ama orta mebleğ deyişmir.
Tövsiye: Hefte sonu satışları artırmaq üçün kampanyaların sayı artırılmalıdır. Müeyyenj edirim ve bonus kampanyaları satışı artırmasına kömek ede biler.
-----------------------------------------
 ölkeler
 hansı ölkede olmasından aslı olmayaraq müşteriler eyni orta mebleğde ödeniş edirler.

 Tövsiye : Qlobal limit siyaseti tetbiq edile biler. ama günümüze baxsaq her ölkede ortalama qazanc eyni olmadığından feqli limit siyasetleri aparıla biler.

 -------------------------------------------
 Fraud yeni dolandırıcılıq analizi
 ümumi saxtakarlıq 63 eded yeni toplamda (1.06%) olmuşdur.
 en çox saxtakarlıq Geyim kategoriyasında olmuştur.
 dolandırıcılıq analizi aşağı olsada geyim kategoriyası risklidir.
 Tövsiye: Geyim kategoriyasında elave yoxlamalar keçirilsin.----------------------------------------------
En aktif müşteri
Qrafikde en çox emelyat eden 20 müşteri gösterilir ve onların ümumi emelyat hecmi digerlerinden qat-qat yüksektir.

Burada ise Pareto prinsipi işleyir. Az sayda müşteri ümumi dövriyenin böyük payını yaradır.

tövsiye: VIP program ve ferdi endirimler istifade olunsun.
-------------------------------------------
En çox ödeniş edilen kategoriya Elektronika ve en çox ödeniş edilen market ise Paytm Mall-dır.

tövsiye: Elktronika kategoriyasına tehlükesizlik tedbirlerinin artırılması.
Paytm Mall startejik terefdaşlıqlar qurmalıdır.

"""